# Hecat configuration for enriching GitHub metadata
# This uses the custom hecat version from feat-commit-history-v2 branch
# to add additional GitHub metadata to awesome-selfhosted-data

steps:
  - name: Update GitHub metadata for all software projects
    module: processors/github_metadata
    module_options:
      source_directory: awesome-selfhosted-data
      gh_metadata_only_missing: False
      gh_commit_history_fetch_months: 12
      gh_commit_history_clean_months: 12
      sleep_time: 60
      batch_size: 30
      max_retries: 3
